//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerShellTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerShellTools.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A collection of the aliases to export from the module..
        /// </summary>
        public static string AliasesToExport_Description {
            get {
                return ResourceManager.GetString("AliasesToExport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aliases to export.
        /// </summary>
        public static string AliasesToExport_DisplayName {
            get {
                return ResourceManager.GetString("AliasesToExport_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Attaching to Process.
        /// </summary>
        public static string AttachErrorTitle {
            get {
                return ResourceManager.GetString("AttachErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remotely debug a process while already attached to a process. Please detach from the currently attached process before trying again..
        /// </summary>
        public static string AttachExistingAttachError {
            get {
                return ResourceManager.GetString("AttachExistingAttachError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot remotely debug a process while in a remote session. Please exit your remote session before trying again..
        /// </summary>
        public static string AttachExistingRemoteError {
            get {
                return ResourceManager.GetString("AttachExistingRemoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The author of the module..
        /// </summary>
        public static string Author_Description {
            get {
                return ResourceManager.GetString("Author_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author_DisplayName {
            get {
                return ResourceManager.GetString("Author_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonLabel {
            get {
                return ResourceManager.GetString("CancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Tools is unable to detach from the process and may now be in an unstable state. You may need to restart Visual Studio..
        /// </summary>
        public static string CleanupErrorMessage {
            get {
                return ResourceManager.GetString("CleanupErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CLR version that this module requires..
        /// </summary>
        public static string ClrVersion_Description {
            get {
                return ResourceManager.GetString("ClrVersion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLR Version.
        /// </summary>
        public static string CLRVersion_DisplayName {
            get {
                return ResourceManager.GetString("CLRVersion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cmdlets to export from the module..
        /// </summary>
        public static string CmdletsToExport_Description {
            get {
                return ResourceManager.GetString("CmdletsToExport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cmdlets to export.
        /// </summary>
        public static string CmdletsToExport_DisplayName {
            get {
                return ResourceManager.GetString("CmdletsToExport_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Signing Certificate.
        /// </summary>
        public static string CodeCertSetting {
            get {
                return ResourceManager.GetString("CodeCertSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the code signing certificate to use when signing scripts..
        /// </summary>
        public static string CodeCertSettingDesc {
            get {
                return ResourceManager.GetString("CodeCertSettingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Parameters.
        /// </summary>
        public static string CommonParametersTipLabel {
            get {
                return ResourceManager.GetString("CommonParametersTipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company name to specify for the module..
        /// </summary>
        public static string CompanyName_Description {
            get {
                return ResourceManager.GetString("CompanyName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName_DisplayName {
            get {
                return ResourceManager.GetString("CompanyName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The copyright information for the module..
        /// </summary>
        public static string Copyright_Description {
            get {
                return ResourceManager.GetString("Copyright_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright_DisplayName {
            get {
                return ResourceManager.GetString("Copyright_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description of the module..
        /// </summary>
        public static string Description_Description {
            get {
                return ResourceManager.GetString("Description_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description_DisplayName {
            get {
                return ResourceManager.GetString("Description_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Detaching From Process.
        /// </summary>
        public static string DetachErrorTitle {
            get {
                return ResourceManager.GetString("DetachErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .NET framework version requried by the module..
        /// </summary>
        public static string DotNetFrameworkVersion_Description {
            get {
                return ResourceManager.GetString("DotNetFrameworkVersion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework Version.
        /// </summary>
        public static string DotNetFrameworkVersion_DisplayName {
            get {
                return ResourceManager.GetString("DotNetFrameworkVersion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (script).
        /// </summary>
        public static string DropDownScriptName {
            get {
                return ResourceManager.GetString("DropDownScriptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the dropdown to view and navigate to other items in this file..
        /// </summary>
        public static string DropDownToolTip {
            get {
                return ResourceManager.GetString("DropDownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This value is not one of the allowed values for parameter &apos;{0}&apos;..
        /// </summary>
        public static string Error_DisallowedValue_1arg {
            get {
                return ResourceManager.GetString("Error_DisallowedValue_1arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; must be of type &apos;{1}&apos;..
        /// </summary>
        public static string Error_TypeMismatch_2args {
            get {
                return ResourceManager.GetString("Error_TypeMismatch_2args", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out to create and initialize the process {0}.
        /// </summary>
        public static string ErrorFailToCreateProcess {
            get {
                return ResourceManager.GetString("ErrorFailToCreateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline not executed because a pipeline is already executing. Pipelines cannot be executed concurrently..
        /// </summary>
        public static string ErrorPipelineBusy {
            get {
                return ResourceManager.GetString("ErrorPipelineBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install and register the PowerGUI VSX debug engine. The first execution of this extension must be run as Administrator to allow a file to be copied to the PowerGUI installation directory and for it to be registered with Visual Studio. For more information see http:\\powerguivsx.codeplex.com. The error that was reported was [{0}]..
        /// </summary>
        public static string FailedToInstallDebugEngine {
            get {
                return ResourceManager.GetString("FailedToInstallDebugEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install debug engine..
        /// </summary>
        public static string FailedToInstallDebugEngineTitle {
            get {
                return ResourceManager.GetString("FailedToInstallDebugEngineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The formats to process within the module..
        /// </summary>
        public static string FormatsToProcess_Description {
            get {
                return ResourceManager.GetString("FormatsToProcess_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats to process.
        /// </summary>
        public static string FormatsToProcess_DisplayName {
            get {
                return ResourceManager.GetString("FormatsToProcess_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions to export from the module..
        /// </summary>
        public static string FunctionsToExport_Description {
            get {
                return ResourceManager.GetString("FunctionsToExport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functions to export.
        /// </summary>
        public static string FunctionsToExport_DisplayName {
            get {
                return ResourceManager.GetString("FunctionsToExport_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralCategory {
            get {
                return ResourceManager.GetString("GeneralCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Help not found for {0}. .
        /// </summary>
        public static string GetHelp_HelpNotFound {
            get {
                return ResourceManager.GetString("GetHelp_HelpNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching Online Help for {0}....
        /// </summary>
        public static string GetHelp_Searching {
            get {
                return ResourceManager.GetString("GetHelp_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function definition is ambiguous. Navigated to first possible definition..
        /// </summary>
        public static string GoToDefinitionAmbiguousMessage {
            get {
                return ResourceManager.GetString("GoToDefinitionAmbiguousMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot navigate to the symbol under the caret..
        /// </summary>
        public static string GoToDefinitionFailureMessage {
            get {
                return ResourceManager.GetString("GoToDefinitionFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Definition.
        /// </summary>
        public static string GoToDefinitionName {
            get {
                return ResourceManager.GetString("GoToDefinitionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unique identifier of the module..
        /// </summary>
        public static string Guid_Description {
            get {
                return ResourceManager.GetString("Guid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Guid_DisplayName {
            get {
                return ResourceManager.GetString("Guid_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighted Braces for PowerShell.
        /// </summary>
        public static string HighlightMatchedBracesTagDisplayName {
            get {
                return ResourceManager.GetString("HighlightMatchedBracesTagDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name of the manifest..
        /// </summary>
        public static string ManifestFileName_Description {
            get {
                return ResourceManager.GetString("ManifestFileName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest File Name.
        /// </summary>
        public static string ManifestFileName_DisplayName {
            get {
                return ResourceManager.GetString("ManifestFileName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Visual Studio.
        /// </summary>
        public static string MessageBoxCaption {
            get {
                return ResourceManager.GetString("MessageBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Tools for Visual Studio Error.
        /// </summary>
        public static string MessageBoxErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Dependency.
        /// </summary>
        public static string MissingDependency {
            get {
                return ResourceManager.GetString("MissingDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Tools for Visual Studio requires at least Windows Management Framework v3, which you do not have installed.
        ///
        ///Would you like to download now?.
        /// </summary>
        public static string MissingPowerShellVersion {
            get {
                return ResourceManager.GetString("MissingPowerShellVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module list.
        /// </summary>
        public static string ModuleList_Description {
            get {
                return ResourceManager.GetString("ModuleList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module list.
        /// </summary>
        public static string ModuleList_DisplayName {
            get {
                return ResourceManager.GetString("ModuleList_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string ModuleSettings {
            get {
                return ResourceManager.GetString("ModuleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module to process.
        /// </summary>
        public static string ModuleToProcess_DisplayName {
            get {
                return ResourceManager.GetString("ModuleToProcess_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the primary or &quot;root&quot; file of the module. When the module is imported, the members that are exported from the root module file are imported into the caller&apos;s session state. Enter the file name of one script module (.psm1) or binary module (.dll)..
        /// </summary>
        public static string ModuleToProess_Description {
            get {
                return ResourceManager.GetString("ModuleToProess_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies script modules (.psm1) and binary modules (.dll) that are imported into the module&apos;s session state. The files in the NestedModules key run in the order in which they are listed in the value..
        /// </summary>
        public static string NestedModules_Description {
            get {
                return ResourceManager.GetString("NestedModules_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nested modules.
        /// </summary>
        public static string NestedModules_DisplayName {
            get {
                return ResourceManager.GetString("NestedModules_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Ok.
        /// </summary>
        public static string OkButtonLabel {
            get {
                return ResourceManager.GetString("OkButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string OutputCategory {
            get {
                return ResourceManager.GetString("OutputCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output directory to copy scripts after completing the build..
        /// </summary>
        public static string OutputDirectory_Description {
            get {
                return ResourceManager.GetString("OutputDirectory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Directory.
        /// </summary>
        public static string OutputDirectory_DisplayName {
            get {
                return ResourceManager.GetString("OutputDirectory_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Module.
        /// </summary>
        public static string OutputTypeSetting {
            get {
                return ResourceManager.GetString("OutputTypeSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether to create a module manifest including the scripts in this project..
        /// </summary>
        public static string OutputTypeSettingDescription {
            get {
                return ResourceManager.GetString("OutputTypeSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following parameter values will be used for this execution.
        /// </summary>
        public static string ParameterEditorTipLabel {
            get {
                return ResourceManager.GetString("ParameterEditorTipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Parameters.
        /// </summary>
        public static string ParameterEditorTitle {
            get {
                return ResourceManager.GetString("ParameterEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Name.
        /// </summary>
        public static string ParameterNameHeaderLabel {
            get {
                return ResourceManager.GetString("ParameterNameHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParameterSetName:.
        /// </summary>
        public static string ParameterSetNameLabel {
            get {
                return ResourceManager.GetString("ParameterSetNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ParameterValueHeaderLabel {
            get {
                return ResourceManager.GetString("ParameterValueHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize PowerShell host for PowerShell Tools.
        /// </summary>
        public static string PowerShellHostInitializeFailed {
            get {
                return ResourceManager.GetString("PowerShellHostInitializeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell host initializing has not yet completed, please try again later..
        /// </summary>
        public static string PowerShellHostInitializingNotComplete {
            get {
                return ResourceManager.GetString("PowerShellHostInitializingNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the name of the Windows PowerShell host program that the module requires. Enter the name of the host program, such as &quot;Windows PowerShell ISE Host&quot; or &quot;ConsoleHost&quot;. Wildcards are not permitted..
        /// </summary>
        public static string PowerShellHostName_Description {
            get {
                return ResourceManager.GetString("PowerShellHostName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Host Name.
        /// </summary>
        public static string PowerShellHostName_DisplayName {
            get {
                return ResourceManager.GetString("PowerShellHostName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the minimum version of the Windows PowerShell host program that works with the module. Enter a version number, such as 1.1..
        /// </summary>
        public static string PowerShellHostVersion_Description {
            get {
                return ResourceManager.GetString("PowerShellHostVersion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Host Version.
        /// </summary>
        public static string PowerShellHostVersion_DisplayName {
            get {
                return ResourceManager.GetString("PowerShellHostVersion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize PowerShell Tools for Visual Studio.
        /// </summary>
        public static string PowerShellToolsInitializeFailed {
            get {
                return ResourceManager.GetString("PowerShellToolsInitializeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the minimum version of Windows PowerShell that will work with this module. Enter 1.0 or 2.0. Requirements for versions greater than 2.0 are not enforced..
        /// </summary>
        public static string PowerShellVersion_Description {
            get {
                return ResourceManager.GetString("PowerShellVersion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Version.
        /// </summary>
        public static string PowerShellVersion_DisplayName {
            get {
                return ResourceManager.GetString("PowerShellVersion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the processor architecture that the module requires. Valid values are x86, AMD64, IA64, and None (unknown or unspecified)..
        /// </summary>
        public static string ProcessorArchitecture_Description {
            get {
                return ResourceManager.GetString("ProcessorArchitecture_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processor Architecture.
        /// </summary>
        public static string ProcessorArchitecture_DisplayName {
            get {
                return ResourceManager.GetString("ProcessorArchitecture_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Tools Remote Debugging (SSL Required).
        /// </summary>
        public static string RemoteDebugTitle {
            get {
                return ResourceManager.GetString("RemoteDebugTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows for debugging of a PowerShell script on a remote machine. Enter the name or address of the machine for which you wish to connect for the qualifier. Port 5986 is the default port but another may be specified. There is no need to specify a transport protocol type (http, tcp, etc.) or username. PowerShell v5.0+ must be installed on the remote machine. Requires a SSL certificate..
        /// </summary>
        public static string RemotePortDescription {
            get {
                return ResourceManager.GetString("RemotePortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PowerShell Tools Remote Debugging.
        /// </summary>
        public static string RemoteUnsecuredDebugTitle {
            get {
                return ResourceManager.GetString("RemoteUnsecuredDebugTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows for debugging of a PowerShell script on a remote machine. Enter the name or address of the machine for which you wish to connect for the qualifier. Port 5985 is the default port but another may be specified. There is no need to specify a transport protocol type (http, tcp, etc.) or username. PowerShell v5.0+ must be installed on the remote machine. Does not require a SSL certificate..
        /// </summary>
        public static string RemoteUnsecuredPortDescription {
            get {
                return ResourceManager.GetString("RemoteUnsecuredPortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the assembly (.dll) files that the module requires. Windows PowerShell loads the specified assemblies before updating types or formats, importing nested modules, or importing the module file that is specified in the value of the ModuleToProcess key..
        /// </summary>
        public static string RequiredAssemblies_Description {
            get {
                return ResourceManager.GetString("RequiredAssemblies_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Assemblies.
        /// </summary>
        public static string RequiredAssemblies_DisplayName {
            get {
                return ResourceManager.GetString("RequiredAssemblies_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies modules that must be in the global session state. If the required modules are not in the global session state, attempts to import this module will fail..
        /// </summary>
        public static string RequiredModules_Description {
            get {
                return ResourceManager.GetString("RequiredModules_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Modules.
        /// </summary>
        public static string RequiredModules_DisplayName {
            get {
                return ResourceManager.GetString("RequiredModules_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies script (.ps1) files that run in the caller&apos;s session state when the module is imported. You can use these scripts to prepare an environment, just as you might use a login script..
        /// </summary>
        public static string ScriptsToProcess_Description {
            get {
                return ResourceManager.GetString("ScriptsToProcess_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripts to process.
        /// </summary>
        public static string ScriptsToProcess_DisplayName {
            get {
                return ResourceManager.GetString("ScriptsToProcess_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Output.
        /// </summary>
        public static string SignOutputSetting {
            get {
                return ResourceManager.GetString("SignOutputSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign the scripts in this project with the specified certificate..
        /// </summary>
        public static string SignOutputSettingDescription {
            get {
                return ResourceManager.GetString("SignOutputSettingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the type files (.ps1xml) that run when the module is imported..
        /// </summary>
        public static string TypesToProcess_Description {
            get {
                return ResourceManager.GetString("TypesToProcess_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types to process.
        /// </summary>
        public static string TypesToProcess_DisplayName {
            get {
                return ResourceManager.GetString("TypesToProcess_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliation asks for an input:.
        /// </summary>
        public static string UserInputRequestMessage {
            get {
                return ResourceManager.GetString("UserInputRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the variables that the module exports. Wildcards are permitted..
        /// </summary>
        public static string VariablesToExport_Description {
            get {
                return ResourceManager.GetString("VariablesToExport_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables to export.
        /// </summary>
        public static string VariablesToExport_DisplayName {
            get {
                return ResourceManager.GetString("VariablesToExport_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the version of the module..
        /// </summary>
        public static string Version_Description {
            get {
                return ResourceManager.GetString("Version_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version_DisplayName {
            get {
                return ResourceManager.GetString("Version_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; is Mandatory..
        /// </summary>
        public static string Warning_MandatoryValueNotSet_1arg {
            get {
                return ResourceManager.GetString("Warning_MandatoryValueNotSet_1arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Auto-generated&gt;.
        /// </summary>
        public static string WatermarkAutoGenerated {
            get {
                return ResourceManager.GetString("WatermarkAutoGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not set).
        /// </summary>
        public static string WatermarkNotSet {
            get {
                return ResourceManager.GetString("WatermarkNotSet", resourceCulture);
            }
        }

        public static string ExplorerWindowTitle
        {
            get
            {
                return ResourceManager.GetString("ExplorerWindowTitle", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Adding test [{0}] in {1} at {2}..
        /// </summary>
        internal static string AddingTestFormat
        {
            get
            {
                return ResourceManager.GetString("AddingTestFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to load Pester module. .
        /// </summary>
        internal static string FailedToLoadPesterModule
        {
            get
            {
                return ResourceManager.GetString("FailedToLoadPesterModule", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parser error. {0}.
        /// </summary>
        internal static string ParserErrorFormat
        {
            get
            {
                return ResourceManager.GetString("ParserErrorFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Searching for tests in [{0}]..
        /// </summary>
        internal static string SearchingForTestsFormat
        {
            get
            {
                return ResourceManager.GetString("SearchingForTestsFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unexpected error! Failed to run tests!.
        /// </summary>
        internal static string UnexpectedError
        {
            get
            {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
    }
}
