name: Cmdlets CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    timeout-minutes: 20

    runs-on: windows-latest 
                            
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: nuget/setup-nuget@v1

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - uses: actions/cache@v4
      id: cache
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

    - uses: actions/cache@v4
      id: cache2
      with:
        path: .\packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.config') }}

    - name: Restore
      shell: pwsh
      run: |
        dotnet restore PowerShellTools.sln
        nuget restore PowerShellTools.sln

    - name: Build Ironman Host
      shell: pwsh
      run: |
        Push-Location IronmanPowerShellHost
        dotnet publish -f net472 -c Release .\IronmanPowerShellHost.csproj
        Pop-Location

    - name: Build Windows Form Designer
      shell: pwsh
      run: |
        msbuild PowerShellTools.sln -t:rebuild -p:Configuration=Release -p:Platform=x64

    - name: Build Cmdlets
      shell: pwsh
      run: |
        .\PowerShellToolsPro.Cmdlets\build.ps1
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: PowerShellTools.Cmdlets
        path: ./PowerShellToolsPro.Cmdlets/out